name: ontime
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  splashscreen: ^1.3.5
  flutter_sparkline: ^0.1.0
  flutter_staggered_grid_view: ^0.4.1
  calendarro: ^1.2.0
  firebase_auth: ^3.1.4
  firebase_core: ^1.8.0
  cloud_firestore: ^2.5.4
  flutter_screenutil: ^5.0.0+2
  table_calendar: ^3.0.3
  firebase_database: any
  google_maps_flutter: ^2.0.11
  platform_device_id: ^1.0.1
  location: ^4.3.0
  flutter_spinkit: ^5.1.0
  flutter_datetime_picker:
    git:
      url: https://github.com/Realank/flutter_datetime_picker.git
  grouped_buttons: ^1.0.3
  permission_handler: ^6.0.1
  device_info: ^2.0.2
  firebase_messaging: ^10.0.9
  flutter_local_notifications: ^9.0.1
  flutter_geofence: ^0.4.1
  geofencing:
    git:
      url: https://github.com/bkonyi/FlutterGeofencing.git

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/gif/loading-gif.gif
    - assets/gif/tick.gif
    - assets/gif/close.gif
    - assets/gif/no_entry.gif
    - assets/logo/logo.png
    - assets/back.jpg
    - assets/logo/logo-white.png
    - assets/logo/profile.jpg

  fonts:

    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.otf

    - family: Poppins-Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.otf

    - family: Sansation-Bold
      fonts:
        - asset: assets/fonts/Sansation-Bold.ttf

    - family: Bitter
      fonts:
        - asset: assets/fonts/Bitter-Bold.ttf
        - asset: assets/fonts/Bitter-Regular.ttf